server:
  port: 66

spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource    # 数据源的类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql的数据库驱动类名称
    url: jdbc:mysql://127.0.0.1:4406/BlossomIM?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  data:
    redis:
      host: 127.0.0.1
      port: 5379
      database: 0
      password: imooc
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
#        username: nacos
#        password: nacos
  rabbitmq:
    host: 127.0.0.1
    port: 5682
    username: imooc
    password: imooc
    virtual-host: BlossomIM

zookeeper:
  curator:
    #    host: 192.168.1.121:2181,192.168.1.122:2181,192.168.1.123:2181
    host: 127.0.0.1:3191
    connectionTimeoutMs: 30000
    sessionTimeoutMs: 3000
    sleepMsBetweenRetry: 2000
    maxRetries: 3
    namespace: itzixi-im